# Generated by Django 5.1.6 on 2025-02-24 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loingdata',
            new_name='Logindata',
        ),
    ]
